version: '3'
services:
    web:
        image: node-api
        ports:
            - "8080:8080"
        restart_policy:
          condition: on-failure
        deploy:
          replicas: 5
    db: 
        image: mysql
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: example
        ports:
            - "3306":"3306"
